repos:
  # Pre-commit hooks (general utilities like fixing whitespace, end of file)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0 # Latest version
    hooks:
      - id: trailing-whitespace # Removes trailing whitespace
      - id: end-of-file-fixer # Ensures files end with a newline
      - id: check-merge-conflict # Ensures no merge conflict markers remain
      - id: check-yaml # Validates YAML syntax

  # Black for code formatting
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: ["--line-length=88", "--target-version=py313"]

  # Ruff for linting and style enforcement (fast alternative to Flake8 + isort)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.3
    hooks:
      - id: ruff
        args: ["--fix", "--target-version=py313"] # Auto-fix issues

  # Python dependencies security checks
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.3
    hooks:
      - id: python-safety-dependencies-check

  # TODO: FIXME: Bandit for security checks
  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.8.0
  #   hooks:
  #     - id: bandit
  #       args:
  #         [
  #           "--recursive",
  #           ".",
  #           "--severity-level",
  #           "high",
  #           "--confidence-level",
  #           "high",
  #         ]
  #       exclude: "./tests|./.venv/" # Exclude test files and "vevn" from security checks
  #       types: [python] # Only run on Python files

  # TODO: FIXME: MyPy for static type checking
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.13.0
  #   hooks:
  #     - id: mypy
  #       args: ["--python-version=3.13", "--strict"]

  # SQLFluff for SQL linting (useful for SQLAlchemy raw queries)
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.3.0
    hooks:
      - id: sqlfluff-lint
        args: ["--dialect", "postgres"] # Adjust dialect if needed

  # Commitizen to enforce semantic commit messages (optional)
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.1.0
    hooks:
      - id: commitizen
