"""Added user and all babies tables

Revision ID: 362c62ee602b
Revises:
Create Date: 2025-01-05 21:09:41.836488

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "362c62ee602b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column(
            "username", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column(
            "first_name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
        sa.Column(
            "last_name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "password", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "baby",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("birthdate", sa.DateTime(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bath",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("time", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("baby_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["baby_id"],
            ["baby.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "diaperchange",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("time", sa.DateTime(), nullable=True),
        sa.Column("pipi", sa.Boolean(), nullable=False),
        sa.Column("poop", sa.Boolean(), nullable=False),
        sa.Column("used_cream", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("baby_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["baby_id"],
            ["baby.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "feeding",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column(
            "type", sa.Enum("BREAST", "BOTTLE", name="feedingtype"), nullable=False
        ),
        sa.Column("left_breast", sa.Integer(), nullable=True),
        sa.Column("right_breast", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("baby_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["baby_id"],
            ["baby.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "measurement",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("time", sa.DateTime(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("weight", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("baby_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["baby_id"],
            ["baby.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "medication",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("dosage", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_vaccine", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("baby_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["baby_id"],
            ["baby.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sleep",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("baby_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["baby_id"],
            ["baby.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "medicationlogs",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("time", sa.DateTime(), nullable=True),
        sa.Column("dosage", sa.Float(), nullable=True),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("medication_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["medication_id"],
            ["medication.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("medicationlogs")
    op.drop_table("sleep")
    op.drop_table("medication")
    op.drop_table("measurement")
    op.drop_table("feeding")
    op.drop_table("diaperchange")
    op.drop_table("bath")
    op.drop_table("baby")
    op.drop_table("user")
    # ### end Alembic commands ###
